# Generated by Django 4.0.1 on 2022-11-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_options_alter_cat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
