# Generated by Django 4.0.1 on 2022-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_address_alter_ads_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Объявление'),
        ),
    ]
